server :
  port : 9090

spring :
  redis :
    host : localhost
    port : 6379
  cloud :
    gateway :
      enabled : true
      httpclient :
        connect-timeout : 100
  profiles :
    active : dev


gateway:
  system-init-load-type: redis

#    password :
management :
  endpoints :
    web :
      exposure :
        include : "*"

debug : true