server :
  port : 8080
  servlet :
    session :
      cookie :
        http-only : true
        name : @project.artifactId@-sid
        path : /
        max-age : 3600
logging :
  level :
    p6spy : info
  file :
    name : @project.artifactId@
    path : ./log
sentry :
  dsn : http://c6715a73355a45ec948d9e0e668c0233@10.168.2.142:9000/2
  sentry-client-name : @project.artifactId@
  logging :
    enabled : false
spring :
  pid :
    file : @project.artifactId@-${server.port:8080}.pid
    fail-on-write-error : true
  application :
    name : @project.artifactId@
  autoconfigure :
    exclude : org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  datasource :
    druid :
      #for production config
      #driver-class-name: com.mysql.cj.jdbc.Driver
      #url: jdbc:mysql://10.168.2.142:3306/gateway?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      #for dev config
      driver-class-name : com.p6spy.engine.spy.P6SpyDriver
      url : jdbc:p6spy:mysql://127.0.0.1:3306/gateway?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&allowPublicKeyRetrieval=true
      username : gateway
      password : gateway
      filter :
        slf4j :
          enabled : true
        stat :
          log-slow-sql : true
          slow-sql-millis : 200
          enabled : true
        wall :
          enabled : true
          db-type : mysql
      web-stat-filter :
        enabled : true
        exclusions : \*.js,\*.gif,\*.jpg,\*.png,\*.css,\*.ico,/druid/*
        url-pattern : /*
      stat-view-servlet :
        #当session 禁用时，不能配置用户密码
        #login-username : admin
        #login-password : admin
        #url-pattern : /druid/*
        enabled : true
      time-between-log-stats-millis : 300000
      test-while-idle : true
      validation-query : select 1
      max-active : 100
      min-idle : 10
  mvc :
    format :
      date : yyyy-MM-dd HH:mm:ss
  jackson :
    date-format : yyyy-MM-dd HH:mm:ss
#  jpa :
#    generate-ddl : true

jasypt :
  encryptor :
    password : 11112222